Lab_1/Models/InputModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Lab_1.Models
{
    public class InputModel
    {
        public string Text { get; set; }
        public IEnumerable<string> ListBoxValues { get; set; }
        public IEnumerable<string> DropdownListValues { get; set; }
        
        public string Radio { get; set; }
    }
}

Lab_1/Models/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Lab_1.Models
{
    public class User
    {
        private static Dictionary<String, User> dictionary = new Dictionary<string, User>() {
            { "cat", new User("cat", "a123","cat@mail.ru",22)},
            { "dog", new User("dog", "b123","dog@gmail.ru",28)},
            { "rat", new User("rat", "c123","rat@ya.ru",36)},
        };

        
        
        

        [Required(ErrorMessage = "Некоректный логин")]
        [RegularExpression(@"^[a-zA-Z][a-zA-Z0-9-_\.]{1,20}$", ErrorMessage = "Используете только латинские буквы и цифры")]
        [Display(Name = "Логин")]
        //[StringLength (25, ErrorMessage = "Логин не должен быть более 25 символов")]
        public string Login { get; set; }

        [Required(ErrorMessage = "Некоректный пароль")]
        [DataType(DataType.Password)]
        [RegularExpression(@"^[a-zA-Z][a-zA-Z0-9-_\.]{1,20}$", ErrorMessage = "Используете только латинские буквы и цифры")]
        public string Password { get; set; }

        [Required(ErrorMessage = "Некоректный пароль")]
        [DataType(DataType.Password)]
        [Compare("Password",ErrorMessage ="Пароли должны совпадать")]
        public string PasswordRepeat { get; set; }

        [Required(ErrorMessage = "Некоректный email")]
        [RegularExpression (@"([a-zA-z])(.+)([a-zA-z])@((g)?mail|yahoo|rambler|yandex|ya)[\.](ru|com)$", ErrorMessage = "Некоректный email")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Некоректный возраст")]
        [Range (18,65,ErrorMessage ="Возраст должен быть в диапазоне от 18 до 65")]
        public int Age { get; set; }





        public User(string login, string password, string email, int age) {
            this.Login = login;
            this.Password = password;
            this.Email = email;
            this.Age = age;
        }


        public User() { }


        public static bool IsValid(String login, String password) {
            login = login.ToLower();
            if (dictionary.ContainsKey(login))
            {
                if (dictionary[login].Password.Equals(password)) {                
                    return true;
                }
            }
            return false;
        }

        public static bool SetUser(User user)
        {
            if (dictionary[user.Login] != null) {
                dictionary.Add(user.Login.ToLower(), user);
                return true;
            }
            return false;
            
        }
        public static User GetUser(string key)
        {
            return dictionary[key];
        }
        
        public static bool CheckUser(string key)
        {
            return dictionary.ContainsKey(key);
        }
    }
}

Lab_1/Controllers/HomeController.cs
using Lab_1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lab_1.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult SignIn()
        {
           
            return View();
        }

        [HttpPost]
        public ActionResult SignIn(User response, string login,string password)
        {
            if (!Models.User.IsValid(login, password))
            {
                Console.WriteLine("post  fail");
                return View("Index");
            }
            else
                return View("Success",Models.User.GetUser(login));
        }

       
    }
}

Lab_1/Controllers/PersonalAccountController.cs
using Lab_1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lab_1.Controllers
{
    public class PersonalAccountController : Controller
    {
        // GET: PersonalAccount
        [HttpGet]
        public ActionResult Index()
        {
            return View("PersonalAccount");
        }
        [HttpPost]
        public ActionResult Index(InputModel model)
        {
            return View("PersonalAccount", model);

        }

    }
}

Lab_1/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Lab_1.Models;

namespace Lab_1.Controllers
{
    public class RegisterController : Controller
    {
        // GET: Register
        [HttpGet]
        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Register(User user)
        {
            if (ModelState.IsValid)
            {
                return View("RegisterSuccess");
 
            }
            return View();
            
        }
    }
}

Lab_1/Controllers/SignIController.cs
using Lab_1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lab_1.Controllers
{
    public class SignInController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult SignIn()
        {
           
            return View();
        }

        [HttpPost]
        public ActionResult SignIn(User response, string login,string password)
        {
            if (!Models.User.IsValid(login, password))
            {
                Console.WriteLine("post  fail");
                return View("Index");
            }
            else
                return View("Success",Models.User.GetUser(login));
        }

       
    }
}

Lab_1/Controllers/SignInController.cs
using Lab_1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lab_1.Controllers
{
    public class SignInController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            
            return View();
        }

        //[HttpGet]
        //public ActionResult SignIn()
        //{
           
          //  return View();
        //}

        [HttpPost]
        public ActionResult Index(User model, string login,string password)
        {
             
            
            if (Models.User.IsValid(login, password))
            {
                
                return View("PersonalAccount");
            }
            else {
                if (Models.User.CheckUser(login))
                {
                    return View("LoginFailed");
                }
                return View("Index");
            }
            
            
        }

       
    }
}

Lab_1/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="">
    

    <div class="col-md-4">

    </div>

    <div class="col-md-4 div-neumorphism">
        <h1>
            Добро пожаловать!
        </h1>
        <h5>
            Войдите в уже существующий аккаунт или зарегистрируйте новый.
        </h5>
        <br />
        <form action="~/Home/SignIn" method="post" name="login_form" target="_self" class="form-sign-in">
            <div class="form-group">
                <label>Ваш логин</label>
                <input type="text" name="login" id="login" placeholder="login" class="form-elem form-control center-block">
            </div>
            <div class="form-group">
                <label>Ваш пароль</label>
                <input type="password" name="password" id="password" placeholder="password" class="form-elem form-control center-block">
            </div>


            <br />
            <button type="submit" id="login_button" class="form-elem btn btn-primary">Войти</button>
            <br />
            <button type="button" id="register_button" class="form-elem btn btn-secondary" onclick="location.href='@Url.Action("Register", "Register")'">Зарегистрироваться</button>
           
        </form>
       
    </div>

    <div class="col-md-4">
    </div>
</div>

Lab_1/Views/Register/Register.cshtml
@model Lab_1.Models.User

@{
    ViewBag.Title = "Register";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="">


    <div class="col-md-4">

    </div>

    <div class="col-md-4 div-neumorphism">
        <h1>
            Форма регистрации
        </h1>
        <h5>
            Создайте свой аккаунт. Это займет минуту вашего времени.
        </h5>
        <br />
        

        @{ Html.BeginForm("Register", "Register", FormMethod.Post, new { @class = "form-sign-in" });}
        <div class="form-group">
            @Html.LabelFor(m => m.Login)
            @Html.TextBoxFor(m => m.Login, new { @class = "form-elem form-control center-block" })
            @Html.ValidationMessageFor(m => m.Login, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Email)
            @Html.TextBoxFor(m => m.Email, new { @class = "form-elem form-control center-block" })
            @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Password)
            @Html.TextBoxFor(m => m.Password, new { @class = "form-elem form-control center-block" })
            @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.PasswordRepeat)
            @Html.TextBoxFor(m => m.PasswordRepeat, new { @class = "form-elem form-control center-block" })
            @Html.ValidationMessageFor(m => m.PasswordRepeat, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Age)
            @Html.TextBoxFor(m => m.Age, new { @class = "form-elem form-control center-block" })
            @Html.ValidationMessageFor(m => m.Age, "", new { @class = "text-danger" })
        </div>


        <br />
        <button type="submit" id="register_button" class="form-elem btn btn-primary">Зарегистрироваться</button>
        <br />
        <p>Уже есть аккаунт?</p>
        <button type="button" id="signIn_button" class="form-elem btn btn-secondary" onclick="location.href='@Url.Action("Index", "SignIn")'">Войти</button>
        @{ Html.EndForm();}
    </div>


  

    @Html.DisplayForModel()

    <div class="col-md-4">
    </div>
</div>

Lab_1/Views/Register/RegisterFailed.cshtml
@{
    ViewBag.Title = "RegisterFailed";
}

<div class="">


    <div class="col-md-4">

    </div>

    <div class="col-md-4 div-neumorphism">
        <h3>
            Пользователь с таким логином уже существует
        </h3>

        <h4>Попробуйте ещё</h4>
        <button type="button" id="register_repeat_button" class="form-elem btn btn-secondary" onclick="location.href='@Url.Action("Register", "Register")'">Войти</button>

        <br />

    </div>

    <div class="col-md-4">
    </div>
</div>

Lab_1/Views/Register/RegisterSuccess.cshtml
@model Lab_1.Models.User

@{
    ViewBag.Title = "Регистрация успешна";
}

<div class="">


    <div class="col-md-4">

    </div>

    <div class="col-md-4 div-neumorphism">
        <h3>
            Вы успешно зарегистрировались
        </h3>
       
        <br />

    </div>

    <div class="col-md-4">
    </div>
</div>

Lab_1/Views/Shared/PersonalAccount.cshtml
@model Lab_1.Models.InputModel

@{
    ViewBag.Title = "PersonalAccount";
}

<div class="">


    <div class="col-md-4">

    </div>

    <div class="col-md-4 div-neumorphism">
        <h1>
            Добро пожаловать!
           
        </h1>
        <br />

        @{Html.BeginForm("Index", "PersonalAccount", FormMethod.Post, new { @class = "form-sign-in" }); }
        <div class="form-group">
            @Html.LabelFor(m => m.Text)
            @Html.TextBoxFor(m => m.Text, new { @class = "form-elem form-control center-block" })

        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.ListBoxValues)
            @Html.ListBoxFor(m => m.ListBoxValues, new MultiSelectList(new string[] { "Audi", "Bmw", "Volvo" }), new { @class = "form-elem form-control center-block" })

        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.DropdownListValues)
            @Html.DropDownListFor(m => m.DropdownListValues, new SelectList(new string[] { "Linux", "Mac OS", "Windows" }), new { @class = "form-elem form-control center-block" })

        </div>

        <div class="form-check">
            @Html.RadioButtonFor(m => m.Radio, "Вариант 1",
                new { @class = "form-check-input", id = "radio1" })
            <label class="form-check-label" for="Radio1">Radio 1</label>

        </div>

        <div class="form-check">
            @Html.RadioButtonFor(m => m.Radio, "Вариант 2",
                new { @class = "form-check-input", id = "radio2" })
            <label class="form-check-label" for="Radio2">Radio 2</label>

        </div>

        <button type="submit" id="input-submit" class="form-elem btn btn-primary">Отправить</button>
        
        @{Html.EndForm();}

        @{
            if (IsPost)
            {   <p>Вы ввели :</p>
                <p>@Html.LabelFor(m => m.Text) : @Html.DisplayFor(m => m.Text)</p>
                <p>@Html.LabelFor(m => m.ListBoxValues) : @Html.DisplayFor(m => m.ListBoxValues)</p>
                <p>@Html.LabelFor(m => m.DropdownListValues) : @Html.DisplayFor(m => m.DropdownListValues)</p>
                <p>@Html.LabelFor(m => m.Radio) : @Html.DisplayFor(m => m.Radio)</p>

            }

        }
    </div>

    <div class="col-md-4">
    </div>
</div>
@section Scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

Lab_1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link type="text/css" rel="stylesheet" href="../../Content/Site.css" />


</head>
<body>
    <div class="container body-content text-center ">
        @RenderBody()
        
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Lab_1/Views/SignIn/Index.cshtml
@model Lab_1.Models.User
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="">


    <div class="col-md-4">

    </div>

    <div class="col-md-4 div-neumorphism">
        <h1>
            Добро пожаловать!
            
        </h1>
        <h5>
            Войдите в уже существующий аккаунт или зарегистрируйте новый.
        </h5>
        <br />

        @{Html.BeginForm("Index", "SignIn", FormMethod.Post, new { @class = "form-sign-in" }); }
        <div class="form-group">
            @Html.LabelFor(m => m.Login)
            @Html.TextBoxFor(m => m.Login, new { @class = "form-elem form-control center-block" })
            @Html.ValidationMessageFor(m => m.Login, "", new { @class = "text-danger" })

        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Password)
            @Html.TextBoxFor(m => m.Password, new { @class = "form-elem form-control center-block" })
            @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
        </div>
        <button type="submit" id="login_button" class="form-elem btn btn-primary">Войти</button>
        <br/>
        <button type="button" id="signIn_button" class="form-elem btn btn-secondary" onclick="location.href='@Url.Action("Register","Register")'">Зарегистрироваться</button>
        @{Html.EndForm();}
    </div>

    <div class="col-md-4">
    </div>
</div>


@section Scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

Lab_1/Views/SignIn/LoginFailed.cshtml
@{
    ViewBag.Title = "LoginFailed";
}

<div class="">


    <div class="col-md-4">

    </div>

    <div class="col-md-4 div-neumorphism">
        <h3>
            Неправильный логин или пароль
        </h3>

        <h4>Попробуйте ещё</h4>
        <button type="button" id="register_repeat_button" class="form-elem btn btn-secondary" onclick="location.href='@Url.Action("Index", "SignIn")'">Войти</button>

        <br />

    </div>

    <div class="col-md-4">
    </div>
</div>

Lab_1/Views/SignIn/PersonalAccount.cshtml
@model Lab_1.Models.InputModel

@{
    ViewBag.Title = "Success";
}

<div class="">


    <div class="col-md-4">

    </div>

    <div class="col-md-4 div-neumorphism">
        <h1>
            Набор значений
        </h1>
        <br />

        @{Html.BeginForm("Index", "PersonalAccount", FormMethod.Post, new { @class = "form-sign-in" }); }
        <div class="form-group">
            @Html.LabelFor(m => m.Text)
            @Html.TextBoxFor(m => m.Text, new { @class = "form-elem form-control center-block" })

        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.ListBoxValues)
            @Html.ListBoxFor(m => m.ListBoxValues, new MultiSelectList(new string[] { "Audi", "Bmw", "Volvo" }), new { @class = "form-elem form-control center-block" })

        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.DropdownListValues)
            @Html.DropDownListFor(m => m.DropdownListValues, new SelectList(new string[] { "Linux", "Mac OS", "Windows" }), new { @class = "form-elem form-control center-block" })

        </div>
        <button type="submit" id="login_button" class="form-elem btn btn-primary">Войти</button>
        @{Html.EndForm();}
    </div>

    <div class="col-md-4">
    </div>
</div>
@section Scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

Lab_1/Views/SignIn/SignIn.cshtml
@model Lab_1.Models.User

@{
    ViewBag.Title = "SignIn";
}

<h2>SignIn</h2>

Lab_1/Views/SignIn/Success.cshtml
@model Lab_1.Models.User

@{
    ViewBag.Title = "Success";
}

<h2>Success</h2>
<p>@Model.GetEmail() @Model.GetPassword()</p>